"""Derive seed-replicate configs from a base arm.

    scripts/delta/py scripts/make_seed_config.py \
        --base configs/base/llama3.2-3b_l27_k2000_bnh_b32k_lam1_d6144_dpc_sampled_tokbias.yaml \
        --seeds 45 46

Writes ``<base>_s<seed>.yaml`` next to the base, changing exactly three things:

    train.seed              -> the new seed
    train.checkpoints_dir   -> the base's dir with _s<seed> appended
    train.keep_checkpoints  -> --keep (default 3)

Nothing else is touched, which is the point: a replicate must differ from its base
in the seed alone, or it stops measuring run-to-run variance and starts measuring
whatever else drifted.

WHY keep_checkpoints DROPS TO 3. The base arm keeps 40 so the trajectory analyses
can read every epoch; a replicate only has to deliver the final epoch. At d6144
that is ~2.4 GB instead of ~33 GB, and at d12288 ~4 GB instead of ~54 GB. Pass
--keep 40 if a replicate really does need its trajectory.

The generated file keeps the base's full comment block after a short header, so the
reasoning behind every loss weight and schedule value travels with the replicate.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HEADER = """# {stem}
#
# SEED REPLICATE {seed} of {base_stem}.
#
# Generated by scripts/make_seed_config.py. Exactly three values differ from the
# base arm — train.seed, train.checkpoints_dir and train.keep_checkpoints — so this
# measures RUN-TO-RUN VARIANCE and nothing else.
#
# WHY REPLICATES. Every GeoAE result before 2026-09-26 is single-seed, so no claim
# has an error bar. The standing rule for comparing arms is to use the WITHIN-run
# margin z - h, because each AE rebuilds its own evaluation population and raw
# cross-arm gaps under ~0.03 are noise (docs/notes/init-arms-dpc-results.md). Seeds
# turn that rule into a measurement.
#
# PAIR IT WITH A BASE ARM AT THE SAME SEED:
#   geoae.interp.fit_balanced_kmeans ... --seed {seed}
# A base fit once at seed 42 and compared against several AE seeds would fold the
# base's own seed variance into the AE's.
#
# Evaluate the FINAL step_*.pt, never best_val.pt: val MSE rises once the cluster
# loss starts at epoch 11, so best_val.pt can be a pre-clustering epoch with
# uninitialised centroids.
#
# ---------------- base config follows (header + values) ----------------
"""


def derive(base: Path, seed: int, keep: int, force: bool) -> Path:
    src = base.read_text()

    if re.search(r"_s\d+$", base.stem):
        sys.exit(f"ABORT: {base.name} is itself a replicate. Derive seeds from the base arm.")

    m = re.search(r'^(?P<indent>\s*)checkpoints_dir:\s*"(?P<dir>[^"]+)"', src, re.M)
    if not m:
        sys.exit(f"ABORT: no quoted train.checkpoints_dir found in {base.name}")
    ckdir = m.group("dir")

    if not re.search(r"^\s*seed:\s*\d+\s*$", src, re.M):
        sys.exit(f"ABORT: no train.seed found in {base.name}")

    out = src
    # seed: the only bare `seed:` key in these configs is train.seed.
    out = re.sub(r"^(\s*)seed:\s*\d+(.*)$", rf"\g<1>seed: {seed}\g<2>", out, count=1, flags=re.M)
    out = out.replace(f'checkpoints_dir: "{ckdir}"', f'checkpoints_dir: "{ckdir}_s{seed}"', 1)

    if re.search(r"^\s*keep_checkpoints:", out, re.M):
        out = re.sub(
            r"^(\s*)keep_checkpoints:\s*\d+.*$",
            rf"\g<1>keep_checkpoints: {keep}       # replicate: only the final epoch is needed",
            out,
            count=1,
            flags=re.M,
        )
    else:
        sys.exit(f"ABORT: no train.keep_checkpoints found in {base.name}")

    dest = base.with_name(f"{base.stem}_s{seed}.yaml")
    if dest.exists() and not force:
        sys.exit(f"ABORT: {dest.name} exists (pass --force to overwrite)")

    dest.write_text(HEADER.format(stem=dest.stem, seed=seed, base_stem=base.stem) + out)
    return dest


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", required=True, type=Path, help="the base arm's config")
    ap.add_argument("--seeds", required=True, type=int, nargs="+")
    ap.add_argument("--keep", type=int, default=3,
                    help="train.keep_checkpoints for the replicate (default 3)")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if not args.base.is_file():
        sys.exit(f"ABORT: no such config: {args.base}")

    for seed in args.seeds:
        dest = derive(args.base, seed, args.keep, args.force)
        print(f"wrote {dest}")


if __name__ == "__main__":
    main()
